============================**EDA Steps**===========================

--------------------**DATA Cleaning and analysis**------------------
1. Read the Data

2. Create categorical and numerical columns

3. Data quick checks

   A) Shape

   B) Size

   C) len

   D) Head

   E) Tail

   F) info
  
5. Missing values analysis

6. Data quality checks or data cleaning

   **Ex:** - Some columns values has some puntuations

       - Column is numerical value

       - but some where cat value available

7. Categorical column analysis

8. Numerical column analysis

        A) Statistical summary

        B) Histogram
   

    Data distribution

   Write your understanding

10. Outlier analysis

    A) Box plot

    B) Treat the outlier

11. Bi variate and multi variate analysis

    A) How one column impact another column

    B) Correlation

    C) Heatmaps

---------------**Feature Engineering**-----------------

10. Encoding: Convert categorical to numerical

    A) Label encoder

    B) OneHotEncodder

11. Scaling:

    A) Standardization

    B) Normalization

12. Transformation(Optional)

-----------------------**Feture selection**------------------

13. Selecting th eimportant fetures for ML model


----------------------**Dimension Reduction methods**------------------

14. Principle Component analysis

    Singular value Decomposition


-----------------------**Develop the ML model**-----------------------

15.

In [8]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [10]:
churn_data=pd.read_csv(r"C:\Users\kkali\Documents\NOTES\telecom_churn_data.csv")

In [12]:
churn_data

,year,customer_id,phone_no,gender,age,no_of_days_subscribed,multi_screen,mail_subscribed,weekly_mins_watched,minimum_daily_mins,maximum_daily_mins,weekly_max_night_mins,videos_watched,maximum_days_inactive,customer_support_calls,churn
0,2015,100198,409-8743,Female,36,62,no,no,148.35,12.2,16.81,82,1,4.0,1,0.0
1,2015,100643,340-5930,Female,39,149,no,no,294.45,7.7,33.37,87,3,3.0,2,0.0
2,2015,100756,372-3750,Female,65,126,no,no,87.30,11.9,9.89,91,1,4.0,5,1.0
3,2015,101595,331-4902,Female,24,131,no,yes,321.30,9.5,36.41,102,4,3.0,3,0.0
4,2015,101653,351-8398,Female,40,191,no,no,243.00,10.9,27.54,83,7,3.0,1,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1995,2015,997132,385-7387,Female,54,75,no,yes,182.25,11.3,20.66,97,5,4.0,2,NaN
1996,2015,998086,383-9255,Male,45,127,no,no,273.45,9.3,30.99,116,3,3.0,1,0.0
1997,2015,998474,353-2080,NaN,53,94,no,no,128.85,15.6,14.60,110,16,5.0,0,0.0
1998,2015,998934,359-7788,Male,40,94,no,no,178.05,10.4,20.18,100,6,NaN,3,0.0
1999,2015,999961,414-1496,Male,37,73,no,no,326.70,10.3,37.03,89,6,3.0,1,1.0

**Step-2: Creating categorical and numerical columns**

In [15]:
num=churn_data.select_dtypes(exclude='object').columns
num

Index(['year', 'customer_id', 'age', 'no_of_days_subscribed',
       'weekly_mins_watched', 'minimum_daily_mins', 'maximum_daily_mins',
       'weekly_max_night_mins', 'videos_watched', 'maximum_days_inactive',
       'customer_support_calls', 'churn'],
      dtype='object')

In [17]:
cat=churn_data.select_dtypes(include='object').columns
cat

Index(['phone_no', 'gender', 'multi_screen', 'mail_subscribed'], dtype='object')

**Step-3: Data Quick checks**

In [20]:
churn_data.shape

(2000, 16)

In [22]:
churn_data.size

32000

In [24]:
len(churn_data)

2000

In [26]:
churn_data.head()

,year,customer_id,phone_no,gender,age,no_of_days_subscribed,multi_screen,mail_subscribed,weekly_mins_watched,minimum_daily_mins,maximum_daily_mins,weekly_max_night_mins,videos_watched,maximum_days_inactive,customer_support_calls,churn
0,2015,100198,409-8743,Female,36,62,no,no,148.35,12.2,16.81,82,1,4.0,1,0.0
1,2015,100643,340-5930,Female,39,149,no,no,294.45,7.7,33.37,87,3,3.0,2,0.0
2,2015,100756,372-3750,Female,65,126,no,no,87.30,11.9,9.89,91,1,4.0,5,1.0
3,2015,101595,331-4902,Female,24,131,no,yes,321.30,9.5,36.41,102,4,3.0,3,0.0
4,2015,101653,351-8398,Female,40,191,no,no,243.00,10.9,27.54,83,7,3.0,1,0.0

In [28]:
churn_data.tail()

,year,customer_id,phone_no,gender,age,no_of_days_subscribed,multi_screen,mail_subscribed,weekly_mins_watched,minimum_daily_mins,maximum_daily_mins,weekly_max_night_mins,videos_watched,maximum_days_inactive,customer_support_calls,churn
1995,2015,997132,385-7387,Female,54,75,no,yes,182.25,11.3,20.66,97,5,4.0,2,NaN
1996,2015,998086,383-9255,Male,45,127,no,no,273.45,9.3,30.99,116,3,3.0,1,0.0
1997,2015,998474,353-2080,NaN,53,94,no,no,128.85,15.6,14.60,110,16,5.0,0,0.0
1998,2015,998934,359-7788,Male,40,94,no,no,178.05,10.4,20.18,100,6,NaN,3,0.0
1999,2015,999961,414-1496,Male,37,73,no,no,326.70,10.3,37.03,89,6,3.0,1,1.0

In [30]:
churn_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2000 entries, 0 to 1999
Data columns (total 16 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   year                    2000 non-null   int64
 1   customer_id             2000 non-null   int64
 2   phone_no                2000 non-null   object
 3   gender                  1976 non-null   object
 4   age                     2000 non-null   int64
 5   no_of_days_subscribed   2000 non-null   int64
 6   multi_screen            2000 non-null   object
 7   mail_subscribed         2000 non-null   object
 8   weekly_mins_watched     2000 non-null   float64
 9   minimum_daily_mins      2000 non-null   float64
 10  maximum_daily_mins      2000 non-null   float64
 11  weekly_max_night_mins   2000 non-null   int64
 12  videos_watched          2000 non-null   int64
 13  maximum_days_inactive   1972 non-null   float64
 14  customer_support_calls  2000 non-null   int64
 15  churn                   1965 non-null   float64
dtypes: float64(5), int64(7), object(4)
memory usage: 250.1+ KB

**Step-4: missing value analysis**

In [33]:
churn_data['no_of_days_subscribed'].unique()

array([ 62, 149, 126, 131, 191,  65,  59,  50, 205,  63, 114, 107,  84,
       142, 137, 100,  99, 115, 194, 104, 170,  76,  94,  81, 119, 138,
       124,  48, 106, 161,  89, 105,  67, 129,  56,  95,  37,  80, 190,
       168, 166,  42,  96,  77,  54,  41,  53,  98,  90, 146,  51,  97,
        55,  74,  86,  75,  27, 163,  44,  92,  45, 140, 122, 132, 103,
       134, 109,  21, 167,  35, 177, 118,  87, 135, 144, 148,  70,  16,
        83,  72,  30,  93,  91, 110, 128,  66,  38,  64, 172,  82,  39,
       108, 162,  10, 156, 101,  68, 111, 112, 127,  61, 158, 192, 136,
       116,  49,  40, 130, 125,   9,  57,  88, 151, 113,  58,  79, 179,
        17, 117, 152, 159, 155,  43, 123,   5, 186, 139,  19, 147,  34,
        73, 121,  78, 153, 171,  85,  29, 102, 165,  36, 150,  31, 201,
       174, 141, 157, 178,  18, 120,  22, 176, 182, 189, 154,   1, 143,
        24,   2,   3, 181, 164, 193, 210,  71,  13,  69, 195, 173,  52,
       133,  46, 184,  47, 145, 197,  25, 199,  60,  32,  33,  28, 169,
        12, 232,  26, 160,  11, 225, 224,  20, 212, 185, 215,  15,  23,
         6, 243, 217, 209,   7, 200, 180, 196, 208])

In [36]:
pd.DataFrame(churn_data.dtypes)

                              0
year                      int64
customer_id               int64
phone_no                 object
gender                   object
age                       int64
no_of_days_subscribed     int64
multi_screen             object
mail_subscribed          object
weekly_mins_watched     float64
minimum_daily_mins      float64
maximum_daily_mins      float64
weekly_max_night_mins     int64
videos_watched            int64
maximum_days_inactive   float64
customer_support_calls    int64
churn                   float64

In [40]:
keys=churn_data.dtypes.keys()
values=churn_data.dtypes.values
pd.DataFrame(zip(keys,values),columns=['Column name','Data type'])

               Column name Data type
0                     year     int64
1              customer_id     int64
2                 phone_no    object
3                   gender    object
4                      age     int64
5    no_of_days_subscribed     int64
6             multi_screen    object
7          mail_subscribed    object
8      weekly_mins_watched   float64
9       minimum_daily_mins   float64
10      maximum_daily_mins   float64
11   weekly_max_night_mins     int64
12          videos_watched     int64
13   maximum_days_inactive   float64
14  customer_support_calls     int64
15                   churn   float64